services:
  - type: web
    name: ai-form-builder-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-generated-survey-and-form-builder.onrender.com

